<?php

namespace Database\Seeders;

use App\Models\EspacioParqueo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EspacioParqueoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        EspacioParqueo::insert([
            [
                'COC_Id' => 1,
                'codigo' => 'A1',
                'TIV_Id' => 1,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'A2',
                'TIV_Id' => 1,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'A3',
                'TIV_Id' => 1,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'A4',
                'TIV_Id' => 1,
                'state' => 'mantenimiento',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'B1',
                'TIV_Id' => 2,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'B2',
                'TIV_Id' => 2,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'B3',
                'TIV_Id' => 2,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'B4',
                'TIV_Id' => 2,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'B5',
                'TIV_Id' => 2,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C1',
                'TIV_Id' => 3,
                'state' => 'pendiente',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C2',
                'TIV_Id' => 3,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C3',
                'TIV_Id' => 3,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C4',
                'TIV_Id' => 3,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C5',
                'TIV_Id' => 3,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C6',
                'TIV_Id' => 3,
                'state' => 'pendiente',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C7',
                'TIV_Id' => 3,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'C8',
                'TIV_Id' => 3,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D1',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D2',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D3',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D4',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D5',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D6',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => 'D7',
                'TIV_Id' => 4,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '1',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '2',
                'TIV_Id' => null,
                'state' => 'pendiente',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '3',
                'TIV_Id' => null,
                'state' => 'pendiente',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '4',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '5',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '6',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '7',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '8',    
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '9',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '10',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '11',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '12',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '13',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '14',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '15',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '16',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 1,
                'codigo' => '17',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],

            [
                'COC_Id' => 1,
                'codigo' => '1',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '2',
                'TIV_Id' => null,
                'state' => 'pendiente',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '3',
                'TIV_Id' => null,
                'state' => 'pendiente',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '4',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '5',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '6',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '7',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '8',    
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '9',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '10',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '11',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '12',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '13',
                'TIV_Id' => null,
                'state' => 'ocupado',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '14',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '15',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '16',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '17',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '18',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '19',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '20',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '21',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '22',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '23',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ],
            [
                'COC_Id' => 4,
                'codigo' => '24',
                'TIV_Id' => null,
                'state' => 'disponible',
                'estado' => 1,
            ]

        ]);
    }
}
